#define ANABOX 1
#define LOGO 1
#define B_ABOUT 6
#define D_PRINT 2
#define PRTBOX 1
#define MENU 0
#define M_DESK 3
#define M_FILE 4
#define M_FORMAT 6
#define M_PRINT 5
#define M_ABOUT 9
#define D_FPRT 4
#define PFBOX 1
#define M_SELECT 18
#define M_SAVE 19
#define M_QUIT 21
#define M_TOFILE 23
#define M_TOPRT 24
#define M_SOURCE 26
#define M_LIST 27
#define D_ANALYZ 3
